### ISSUE TITLE
SMAPI couldn't load the game executable

### ISSUE THREAD

**Issue by chaiguy22** [Yagisan/The-Bustling-Valley#4]
Hi,

I followed the instructions in the code section and used Wabbajack to download the modpack, I made sure to install a clean copy of Stardew Valley, but I keep getting this error when launching SMAPI through Mod Organizer.

Oops! SMAPI couldn't load the game executable. The technical details below may have more info.

Technical details: System.BadImageFormatException: Could not load file or assembly 'Stardew Valley' or one of its dependencies. An attempt was made to load a program with an incorrect format.
File name: 'Stardew Valley'
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Boolean throwOnError)
   at StardewModdingAPI.Program.AssertGamePresent() in C:\source\_Stardew\SMAPI\src\SMAPI\Program.cs:line 80

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

Game has ended. Press any key to exit.

**Comment by Yagisan** [comment]
I need the **entire** SMAPI log to even diagnose the issue.

Please upload your SMAPI log to [https://smapi.io/log](https://smapi.io/log) (see instructions on that page) and share the link here with your report.

Just to confirm, you are using SMAPI 3.13.2 or later, with Stardew Valley 1.5.6 ?

**Comment by Yagisan** [comment]
Closing as I can not replicate this.
